"""testmigrate

Revision ID: bf477a55f253
Revises: 29ea6d3c8415
Create Date: 2023-10-04 14:33:37.711994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf477a55f253'
down_revision = '29ea6d3c8415'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test1', sa.Integer(), nullable=True),
    sa.Column('test2', sa.String(), nullable=True),
    sa.Column('test3', sa.REAL(), nullable=True),
    sa.Column('nametest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_id'), 'test', ['id'], unique=False)
    op.add_column('role', sa.Column('isusewebsite', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'isusewebsite')
    op.drop_index(op.f('ix_test_id'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
