"""updade

Revision ID: 29ea6d3c8415
Revises: de2d2eaad961
Create Date: 2023-10-02 15:49:37.267662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ea6d3c8415'
down_revision = 'de2d2eaad961'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'isusewebsite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('isusewebsite', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
